/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejemplojavaswim;

import javax.swing.JOptionPane;

/**
 *
 * @author padil
 */
public class Ejemplo extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo
     */
    public Ejemplo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbNombres = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbCarrera = new javax.swing.JLabel();
        lbTituloVentana = new javax.swing.JLabel();
        lbCiclo = new javax.swing.JLabel();
        cbCarrera = new javax.swing.JComboBox<>();
        txNombres = new javax.swing.JTextField();
        txApellidos = new javax.swing.JTextField();
        txCorreo = new javax.swing.JTextField();
        rbCiclo2 = new javax.swing.JRadioButton();
        rbCiclo1 = new javax.swing.JRadioButton();
        btRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNombres.setText("Nombres:");

        lbApellidos.setText("Apellidos:");

        lbCorreo.setText("Correo:");

        lbCarrera.setText("Carrera");

        lbTituloVentana.setText("Datos del Alumno");

        lbCiclo.setText("Ciclo Actual:");

        cbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Ing. Sistemas", "Ing. Industrial", "Ing. Electrica", "Ing. Agronegocios" }));

        txCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCorreoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCiclo2);
        rbCiclo2.setText("Ciclo 02");

        buttonGroup1.add(rbCiclo1);
        rbCiclo1.setText("Ciclo 01");

        btRegistrar.setText("REGISTRAR");
        btRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCarrera)
                            .addComponent(lbCorreo)
                            .addComponent(lbApellidos)
                            .addComponent(lbNombres))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbCiclo1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbCiclo2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txNombres, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbCarrera, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btRegistrar)
                                    .addComponent(lbTituloVentana)))))
                    .addComponent(lbCiclo))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbTituloVentana)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombres)
                    .addComponent(txNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbApellidos)
                    .addComponent(txApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCorreo)
                    .addComponent(txCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCarrera)
                    .addComponent(cbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbCiclo1)
                        .addComponent(rbCiclo2))
                    .addComponent(lbCiclo))
                .addGap(18, 18, 18)
                .addComponent(btRegistrar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarActionPerformed
        String CicloActual = "";
        String Carrera = "";
        String CarreraSeleccionada = (String)this.cbCarrera.getSelectedItem();
        String nombres = this.txNombres.getText().trim();
        String apellidos = this.txApellidos.getText().trim();
        String correo = this.txCorreo.getText().trim();
        
        if (nombres.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if (apellidos.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un apellido.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if (correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un correo.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if("Seleccione una opcion".equals(CarreraSeleccionada)){
            Carrera = "-1";
            JOptionPane.showMessageDialog(this, "Seleccione una carrera.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if(this.rbCiclo1.isSelected()){
            CicloActual = "01";
        }else if(this.rbCiclo2.isSelected()){
            CicloActual = "02";
        }else{
            CicloActual = "-1";
            JOptionPane.showMessageDialog(this, "Seleccione un ciclo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        if(!"-1".equals(CicloActual) && !"-1".equals(Carrera)){
            JOptionPane.showMessageDialog(
            this, "Registro exitoso de " 
                    + this.txNombres.getText() 
                    + " " 
                    + this.txApellidos.getText() 
                    + " estudiante de la carrera de " 
                    + this.cbCarrera.getSelectedItem() 
                    + " con el correo " 
                    + this.txCorreo.getText() 
                    + " en el ciclo " 
                    + CicloActual
                    + "." 
            );
        }
        
    }//GEN-LAST:event_btRegistrarActionPerformed

    private void txCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCorreoActionPerformed
        // TODO add your handling code here: NOT USING IT
    }//GEN-LAST:event_txCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCarrera;
    private javax.swing.JLabel lbApellidos;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCiclo;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbNombres;
    private javax.swing.JLabel lbTituloVentana;
    private javax.swing.JRadioButton rbCiclo1;
    private javax.swing.JRadioButton rbCiclo2;
    private javax.swing.JTextField txApellidos;
    private javax.swing.JTextField txCorreo;
    private javax.swing.JTextField txNombres;
    // End of variables declaration//GEN-END:variables
}
