/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicio2guia1;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author padil
 */
public class Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblControl = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblCUM = new javax.swing.JLabel();
        lblCiclo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbCarrera = new javax.swing.JComboBox<>();
        cmbCiclo = new javax.swing.JComboBox<>();
        txtCUM = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        lblUV = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbMateria1 = new javax.swing.JComboBox<>();
        cmbMateria3 = new javax.swing.JComboBox<>();
        cmbMateria2 = new javax.swing.JComboBox<>();
        cmbMateria4 = new javax.swing.JComboBox<>();
        cmbMateria5 = new javax.swing.JComboBox<>();
        cmbUV1 = new javax.swing.JComboBox<>();
        cmbUV5 = new javax.swing.JComboBox<>();
        cmbUV2 = new javax.swing.JComboBox<>();
        cmbUV3 = new javax.swing.JComboBox<>();
        cmbUV4 = new javax.swing.JComboBox<>();
        lblEstado1 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();
        lblEstado4 = new javax.swing.JLabel();
        lblEstado5 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        txtMateria1 = new javax.swing.JTextField();
        txtMateria2 = new javax.swing.JTextField();
        txtMateria4 = new javax.swing.JTextField();
        txtMateria3 = new javax.swing.JTextField();
        txtMateria5 = new javax.swing.JTextField();
        lblUV1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL DE NOTAS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblControl.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        lblControl.setText("CONTROL DE NOTAS");

        lblNombre.setText("Nombre");

        lblCarrera.setText("Carrera");

        lblCUM.setText("CUM");

        lblCiclo.setText("Ciclo");

        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ing. Sistemas", "Ing. Industrial", "Ing. Agronegocios", "Ing. Electrica" }));

        cmbCiclo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ciclo 01", "Ciclo 02" }));

        txtCUM.setEditable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ejercicio2guia1/logo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblMateria.setText("Materia");

        lblUV.setText("UV");

        lblEstado.setText("Estado");

        cmbMateria1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "IO" }));

        cmbMateria3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "BDII" }));

        cmbMateria2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Elect" }));

        cmbMateria4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "DSI" }));

        cmbMateria5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Legs" }));

        cmbUV1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3.0 UV", "4.0 UV" }));

        cmbUV5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3.0 UV", "4.0 UV" }));

        cmbUV2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3.0 UV", "4.0 UV" }));

        cmbUV3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3.0 UV", "4.0 UV" }));

        cmbUV4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3.0 UV", "4.0 UV" }));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblResultado.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        lblUV1.setText("Nota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblNombre)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lblCarrera)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCiclo)
                                .addGap(56, 56, 56)
                                .addComponent(lblCUM))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblMateria)
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCUM, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblUV)
                                        .addGap(50, 50, 50)
                                        .addComponent(lblUV1)
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEstado2)
                                            .addComponent(lblEstado3)
                                            .addComponent(lblEstado4)
                                            .addComponent(lblEstado5)
                                            .addComponent(lblEstado)
                                            .addComponent(lblEstado1)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblResultado))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblControl)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblControl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblCarrera)
                    .addComponent(lblCUM)
                    .addComponent(lblCiclo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCUM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMateria)
                            .addComponent(lblUV)
                            .addComponent(lblEstado)
                            .addComponent(lblUV1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado1)
                            .addComponent(txtMateria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado2)
                            .addComponent(txtMateria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUV3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado3)
                            .addComponent(txtMateria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUV4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado4)
                            .addComponent(txtMateria4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbUV5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado5)
                            .addComponent(txtMateria5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
  
        //VARIABLES
        String Carrera = "";
        String CicloActual = "";
        String Materia1 = "";
        String Materia2 = "";
        String Materia3 = "";
        String Materia4 = "";
        String Materia5 = "";
        String nombres = this.txtNombre.getText().trim();
        String CarreraSeleccionada = (String)this.cmbCarrera.getSelectedItem(); 
        String CicloSeleccionado = (String)this.cmbCiclo.getSelectedItem();
        String Materia1Seleccionada = (String)this.cmbMateria1.getSelectedItem(); 
        String Materia2Seleccionada = (String)this.cmbMateria2.getSelectedItem();
        String Materia3Seleccionada = (String)this.cmbMateria3.getSelectedItem(); 
        String Materia4Seleccionada = (String)this.cmbMateria4.getSelectedItem();
        String Materia5Seleccionada = (String)this.cmbMateria5.getSelectedItem();
        String textoNota1 = txtMateria1.getText();
        String textoNota2 = txtMateria2.getText();
        String textoNota3 = txtMateria3.getText();
        String textoNota4 = txtMateria4.getText();
        String textoNota5 = txtMateria5.getText();
        int Nota1;
        int Nota2;
        int Nota3;
        int Nota4;
        int Nota5;
        int Aprobadas = 0;
        int Reprobadas = 0;
        double CUM = 0;
        double UVR1 = 0;
        double UVR2 = 0;
        double UVR3 = 0;
        double UVR4 = 0;
        double UVR5 = 0;
        int UV1;
        int UV2;
        int UV3;
        int UV4;
        int UV5;
        String UV1Seleccionado = (String) cmbUV1.getSelectedItem();
        String UV2Seleccionado = (String) cmbUV2.getSelectedItem();
        String UV3Seleccionado = (String) cmbUV3.getSelectedItem();
        String UV4Seleccionado = (String) cmbUV4.getSelectedItem();
        String UV5Seleccionado = (String) cmbUV5.getSelectedItem();
        DecimalFormat df = new DecimalFormat("#.##");
 
        //VALIDACIONES
        if (nombres.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un nombre.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
        if ("Seleccione".equals(CarreraSeleccionada)) {
        Carrera = "-1";
        JOptionPane.showMessageDialog(this, "Seleccione una carrera.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Carrera = CarreraSeleccionada;
        }
    
        if ("Seleccione".equals(CicloSeleccionado)) {
        CicloActual = "-1";
        JOptionPane.showMessageDialog(this, "Seleccione un ciclo.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            CicloActual = CicloSeleccionado.substring(CicloSeleccionado.length() - 2);
        }
        
        if ("Select".equals(Materia1Seleccionada)) {
        Materia1 = "-1";
        JOptionPane.showMessageDialog(this, "Seleccione una materia 1.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Materia1 = Materia1Seleccionada;
        }
        
        if ("Select".equals(Materia2Seleccionada)) {
        Materia1 = "-1";
        JOptionPane.showMessageDialog(this, "Seleccione una materia 2.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Materia2 = Materia2Seleccionada;
        }
        
        if ("Select".equals(Materia3Seleccionada)) {
        Materia1 = "-1";
        JOptionPane.showMessageDialog(this, "Seleccione una materia 3.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Materia3 = Materia3Seleccionada;
        }
        
        if ("Select".equals(Materia4Seleccionada)) {
        Materia1 = "-1";
        JOptionPane.showMessageDialog(this, "Seleccione una materia 4.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Materia4 = Materia4Seleccionada;
        }
        
        if ("Select".equals(Materia5Seleccionada)) {
        Materia1 = "-1";
        JOptionPane.showMessageDialog(this, "Seleccione una materia 5.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Materia5 = Materia5Seleccionada;
        }
        
        //BLOQUE NOTA 1
        try {
            Nota1 = Integer.parseInt(textoNota1);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para Nota 1.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Nota1 < 6 && Nota1 >= 0){
            lblEstado1.setText("Reprobada");
            Reprobadas++;
        }else if(Nota1 <= 10){
            lblEstado1.setText("Aprobada");
            Aprobadas++;
        }else {
            lblEstado1.setText("Invalida");
        }
        
        //BLOQUE NOTA 2
        try {
            Nota2 = Integer.parseInt(textoNota2);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para Nota 2.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Nota2 < 6 && Nota2 >= 0){
            lblEstado2.setText("Reprobada");
            Reprobadas++;
        }else if(Nota2 <= 10){
            lblEstado2.setText("Aprobada");
            Aprobadas++;
        }else {
            lblEstado2.setText("Invalida");
        }
        
        //BLOQUE NOTA 3
        try {
            Nota3 = Integer.parseInt(textoNota3);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para Nota 3.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Nota3 < 6 && Nota3 >= 0){
            lblEstado3.setText("Reprobada");
            Reprobadas++;
        }else if(Nota3 <= 10){
            lblEstado3.setText("Aprobada");
            Aprobadas++;
        }else {
            lblEstado3.setText("Invalida");
        }
        
        //BLOQUE NOTA 4
        try {
            Nota4 = Integer.parseInt(textoNota4);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para Nota 4.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Nota4 < 6 && Nota4 >= 0){
            lblEstado4.setText("Reprobada");
            Reprobadas++;
        }else if(Nota4 <= 10){
            lblEstado4.setText("Aprobada");
            Aprobadas++;
        }else {
            lblEstado4.setText("Invalida");
        }
        
        //BLOQUE NOTA 5
        try {
            Nota5 = Integer.parseInt(textoNota5);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para Nota 5.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Nota5 < 6 && Nota5 >= 0){
            lblEstado5.setText("Reprobada");
            Reprobadas++;
        }else if(Nota5 <= 10){
            lblEstado5.setText("Aprobada");
            Aprobadas++;
        }else {
            lblEstado5.setText("Invalida");
        }
        
        //CALCULO UVs
         if ("3.0 UV".equals(UV1Seleccionado)) {
            UV1 = 3;
            UVR1 = Nota1 * 3;
        } else if ("4.0 UV".equals(UV1Seleccionado)) {
            UV1 = 4;
            UVR1 = Nota1 * 4;
        } else {
            UV1 = -1;
            JOptionPane.showMessageDialog(this, "Seleccione un UV Valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("3.0 UV".equals(UV2Seleccionado)) {
            UV2 = 3;
            UVR2 = Nota2 * 3;
        } else if ("4.0 UV".equals(UV2Seleccionado)) {
            UV2 = 4;
            UVR2 = Nota2 * 4;
        } else {
            UV2 = -1;
            JOptionPane.showMessageDialog(this, "Seleccione un UV Valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("3.0 UV".equals(UV3Seleccionado)) {
            UV3 = 3;
            UVR3 = Nota3 * 3;
        } else if ("4.0 UV".equals(UV3Seleccionado)) {
            UV3 = 4;
            UVR3 = Nota3 * 4;
        } else {
            UV3 = -1;
            JOptionPane.showMessageDialog(this, "Seleccione un UV Valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("3.0 UV".equals(UV4Seleccionado)) {
            UV4 = 3;
            UVR4 = Nota4 * 3;
        } else if ("4.0 UV".equals(UV4Seleccionado)) {
            UV4 = 4;
            UVR4 = Nota4 * 4;
        } else {
            UV4 = -1;
            JOptionPane.showMessageDialog(this, "Seleccione un UV Valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if ("3.0 UV".equals(UV5Seleccionado)) {
            UV5 = 3;
            UVR5 = Nota5 * 3;
        } else if ("4.0 UV".equals(UV5Seleccionado)) {
            UV5 = 4;
            UVR5 = Nota5 * 4;
        } else {
            UV5 = -1;
            JOptionPane.showMessageDialog(this, "Seleccione un UV Valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        //CALCULO DEL CUM
        CUM = (UVR1 + UVR2 + UVR3 + UVR4 + UVR5)/(UV1 + UV2 + UV3 + UV4 + UV5);
        
        //IMPRESION DEL RESULTADO
         lblResultado.setText(this.txtNombre.getText() 
                 + ", su estado actual es de: " 
                 + Aprobadas 
                 + " materias aprobadas, " 
                 + Reprobadas 
                 + " materias reprobadas y su CUM actual es de " 
                 + df.format(CUM));
         txtCUM.setText(df.format(CUM));
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JComboBox<String> cmbCiclo;
    private javax.swing.JComboBox<String> cmbMateria1;
    private javax.swing.JComboBox<String> cmbMateria2;
    private javax.swing.JComboBox<String> cmbMateria3;
    private javax.swing.JComboBox<String> cmbMateria4;
    private javax.swing.JComboBox<String> cmbMateria5;
    private javax.swing.JComboBox<String> cmbUV1;
    private javax.swing.JComboBox<String> cmbUV2;
    private javax.swing.JComboBox<String> cmbUV3;
    private javax.swing.JComboBox<String> cmbUV4;
    private javax.swing.JComboBox<String> cmbUV5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCUM;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCiclo;
    private javax.swing.JLabel lblControl;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblEstado3;
    private javax.swing.JLabel lblEstado4;
    private javax.swing.JLabel lblEstado5;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblUV;
    private javax.swing.JLabel lblUV1;
    private javax.swing.JTextField txtCUM;
    private javax.swing.JTextField txtMateria1;
    private javax.swing.JTextField txtMateria2;
    private javax.swing.JTextField txtMateria3;
    private javax.swing.JTextField txtMateria4;
    private javax.swing.JTextField txtMateria5;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
